n1= int(input('Qual numero você quer saber sua tabuada: '))
print('-' * 12)
print('{} x 0 = {}'.format(n1, n1*0))
print('{} x 1 = {}'.format(n1, n1*1))
print('{} x 2 = {}'.format(n1, n1*2))
print('{} x 3 = {}'.format(n1, n1*3))
print('{} x 4 = {}'.format(n1, n1*4))
print('{} x 5 = {}'.format(n1, n1*5))
print('{} x 6 = {}'.format(n1, n1*6))
print('{} x 7 = {}'.format(n1, n1*7))
print('{} x 8 = {}'.format(n1, n1*8))
print('{} x 9 = {}'.format(n1, n1*9))
print('{} x 10 = {}'.format(n1, n1*10))
print('-' * 12)